apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      name: spring-app
      labels:
        app: spring-app
    spec:
      containers:
        - name: title
          image: springimg:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
              hostPort: 8086
              protocol: TCP
      restartPolicy: Always
      