apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      name: spring-app
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app-service
          image: csserviceimg:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
              hostPort: 8086
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: "1Gi"
              memory: 500Mi
          env:
            - name: DB_URL
              value: "123"
      restartPolicy: Always
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: default
spec:
  selector:
    app: spring-app
  ports:
    - name: http
      port: 8056
      targetPort: 8056
      nodePort: 30005
      protocol: TCP
  type: NodePort
