apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  selector:
    app: spring-app
  ports:
    - name: http
      port: 8056
      targetPort: 8056
      nodePort: 30005
  type: NodePort
  